name: Bradley Rosenfeld
markdown: redcarpet
pygments: false
permalink: pretty
paginate: 5
paginate_path: writing/page/:num
navigation:
- text: Portfolio
  url: /portfolio/
- text: Writing
  url: /writing/
  layout: post
- text: Contact
  url: /contact/