name: Bradley Rosenfeld
markdown: redcarpet
highlighter: false
exclude:
  - node_modules
  - bower_components
  - Gruntfile.js
  - package.json
  - readme.md
permalink: /writing/:year/:month/:day/:title/
paginate: 8
paginate_path: writing/page/:num
baseurl: http://bradleyrosenfeld.com
navigation:
- text: Portfolio
  url: /portfolio/
  fullurl: /portfolio/index.html
- text: Writing
  url: /writing/
  fullurl: /writing/index.html
  layout: post
- text: Contact
  url: /contact/
  fullurl: /contact/index.html
email: thatguy@bradleyrosenfeld.com
social:
- name: Twitter
  url: http://twitter.com/BoringCode/
  icon: twitter
- name: Stack Overflow
  url: http://stackoverflow.com/users/245909/boringcode
  icon: stackoverflow
- name: Google+
  url: https://plus.google.com/u/0/103911801470461386422/
  icon: googleplus
- name: Github
  url: http://github.com/BoringCode/
  icon: github
- name: Vimeo
  url: https://vimeo.com/bradleyrosenfeld
  icon: vimeo
- name: reddit
